#!/usr/bin/env python3
"""
RSDK Object Script Generator
Generate RSDK object scripts from parameters.
"""

import sys
import os

TEMPLATE = '''// RSDKv5 Object Script
// Object Name: {object_name}
// Type ID: {type_id}
// Description: {description}
// Generated by RSDK Script Generator

Create:
    // Position and movement
    self.position.x = 0
    self.position.y = 0
    self.velocity.x = {velocity_x}
    self.velocity.y = {velocity_y}
    
    // State
    self.active = true
    self.visible = true
    self.direction = {direction}
    
    // Sprite and animation
    self.spriteIndex = {sprite_index}
    self.animIndex = 0
    self.frameIndex = 0
    
    // Hitbox
    self.hitbox[0].left = {hitbox_left}
    self.hitbox[0].top = {hitbox_top}
    self.hitbox[0].right = {hitbox_right}
    self.hitbox[0].bottom = {hitbox_bottom}
    
    // Custom properties
    self.timer = 0
    self.state = 0
    
    return

Update:
    // Update timer
    self.timer += 1
    
    // State machine
    if self.state == 0
        // State 0: Default state
        {update_logic}
    endif
    
    // Movement
    self.position.x += self.velocity.x
    self.position.y += self.velocity.y
    
    // Animation
    Animate()
    
    return

Draw:
    DrawSprite(self.spriteIndex, self.animIndex, self.position.x, self.position.y, self.direction, 0)
    return

StageLoad:
    return
'''

def generate_object_script(params):
    """Generate RSDK object script from parameters."""
    
    # Default parameters
    defaults = {
        'object_name': 'NewObject',
        'type_id': '0',
        'description': 'Auto-generated RSDK object',
        'velocity_x': '0',
        'velocity_y': '0',
        'direction': '0',
        'sprite_index': '0',
        'hitbox_left': '-16',
        'hitbox_top': '-16',
        'hitbox_right': '16',
        'hitbox_bottom': '0',
        'update_logic': '// Add your update logic here',
    }
    
    # Merge with provided parameters
    defaults.update(params)
    
    # Generate script
    script = TEMPLATE.format(**defaults)
    return script

def main():
    if len(sys.argv) < 2:
        print("RSDK Object Script Generator")
        print("\nUsage:")
        print("  python generate_object.py <output_file> [options]")
        print("\nOptions:")
        print("  --name NAME          Object name (default: NewObject)")
        print("  --type-id ID        Object type ID (default: 0)")
        print("  --desc DESCRIPTION  Object description")
        print("  --vx VELOCITY      X velocity (default: 0)")
        print("  --vy VELOCITY      Y velocity (default: 0)")
        print("  --sprite INDEX      Sprite index (default: 0)")
        print("  --hitbox L,T,R,B   Hitbox (default: -16,-16,16,0)")
        print("\nExample:")
        print("  python generate_object.py Obj_Enemy.txt --name Enemy --type-id 100 --vx -2")
        sys.exit(1)
    
    output_file = sys.argv[1]
    params = {}
    
    # Parse arguments
    i = 2
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg == '--name' and i + 1 < len(sys.argv):
            params['object_name'] = sys.argv[i + 1]
            i += 2
        elif arg == '--type-id' and i + 1 < len(sys.argv):
            params['type_id'] = sys.argv[i + 1]
            i += 2
        elif arg == '--desc' and i + 1 < len(sys.argv):
            params['description'] = sys.argv[i + 1]
            i += 2
        elif arg == '--vx' and i + 1 < len(sys.argv):
            params['velocity_x'] = sys.argv[i + 1]
            i += 2
        elif arg == '--vy' and i + 1 < len(sys.argv):
            params['velocity_y'] = sys.argv[i + 1]
            i += 2
        elif arg == '--sprite' and i + 1 < len(sys.argv):
            params['sprite_index'] = sys.argv[i + 1]
            i += 2
        elif arg == '--hitbox' and i + 1 < len(sys.argv):
            parts = sys.argv[i + 1].split(',')
            if len(parts) == 4:
                params['hitbox_left'] = parts[0]
                params['hitbox_top'] = parts[1]
                params['hitbox_right'] = parts[2]
                params['hitbox_bottom'] = parts[3]
            i += 2
        else:
            i += 1
    
    # Generate script
    script = generate_object_script(params)
    
    # Write to file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(script)
    
    print(f"✅ Generated RSDK object script: {output_file}")
    print(f"   Object Name: {params.get('object_name', 'NewObject')}")
    print(f"   Type ID: {params.get('type_id', '0')}")

if __name__ == '__main__':
    main()
